github.com:
    users:
        AstryxHQ:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: AstryxHQ
